# Generated by Django 3.2.1 on 2023-05-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdomotic', '0005_alter_sensor_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interruptor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='reloj',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='interruptor',
            name='publicId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reloj',
            name='publicId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='publicId',
            field=models.CharField(max_length=50),
        ),
    ]
