# Generated by Django 3.2.1 on 2023-05-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysdomotic', '0007_alter_reloj_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reloj',
            name='state',
        ),
    ]
